sudo: required
language: php
env:
  DOCKER_COMPOSE_VERSION: 1.25.0
services:
- docker
addons:
  ssh_known_host:
  - 165.227.179.245
  - andrewadcock.com
before_install:
- openssl aes-256-cbc -K $encrypted_e626a03f7ac6_key -iv $encrypted_e626a03f7ac6_iv
  -in travis_rsa.enc -out travis_rsa -d
- chmod 600 travis_rsa
- mv travis_rsa ~/.ssh/id_rsa
- cd symfony
- composer install
#- docker build -t aadcock/andrewadcockcom -f Dockerfile.dev .
#- docker run -d -p80:8080 aadcock/andrewadcockcom

script:
  - php ./vendor/bin/simple-phpunit
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
