<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWdCPBHO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWdCPBHO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWdCPBHO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWdCPBHO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWdCPBHO\App_KernelDevDebugContainer([
    'container.build_hash' => 'WdCPBHO',
    'container.build_id' => '22190616',
    'container.build_time' => 1578931302,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWdCPBHO');
