easy_admin:
    site_name: AndrewAdcock.com
    design:
        menu:
            - {label: "Entities"}
            - label: "Posts"
              children:
                - {entity: Article, label: "List Posts", icon: "th-list"}
                - {entity: Article, label: "New Post", icon: "plus", params: {action: 'new'}}
            - label: "Category"
              children:
                  - {entity: Category, label: "List Categories", icon: "th-list"}
                  - {entity: Category, label: "New Category", icon: "plus", params: {action: 'new'}}
            - {label: "Settings"}
            - label: "Users"
              children:
                  - {entity: User, label: "List Users", icon: "th-list"}
                  - {entity: User, label: "New User", icon: "plus", params: {action: 'new'}}
    entities:
        Article:
            class: App\Entity\Article
            form:
                fields:
                    - title
                    - slug
                    - content
                    - publishedAt
                    - Author
                    - ImageFilename
                    - categories
        Category:
            class: App\Entity\Category
        User:
            class: App\Entity\User
