easy_admin:
    site_name: AndrewAdcock.com
    design:
        brand_color: '#384e39'
    entities:
        Article:
            class: App\Entity\Article
            form:
                fields:
                    - title
                    - slug
                    - content
                    - publishedAt
                    - Author
                    - ImageFilename
                    - categories
        Categories:
            class: App\Entity\Category
        User:
            class: App\Entity\User
